### PR TITLE
add iOS instructions

### PR DESCRIPTION
**Pull request by vesparny**
even if I am not sure if it works as I am alone on the default channel 🙃

screen shot 2018-06-22 at 15 36 07

### CODE REVIEW

**Comment by nikolaiwarner** [comment]
Yes, at the moment iOS is not working. You might want to add that it's still a work in progress for iOS.

**Comment by vesparny** [comment]
do you already know where is the problem for iOS?
If so, I'd be happy to look into it.

**Comment by nikolaiwarner** [comment]
The problem is somewhere in nodejs-mobile-react-native, I think. @jimpick has been hacking at it but more hands on it the better. 

There's a discussion going in the `cabal-dev` channel on this cabal, if you'd like to join in: dat://59813e3169b4b2a6d3741b077f80cce014d84d67b4a8f9fa4c19605b5cff637f

**Comment by vesparny** [comment]
I'm in

**Comment by staltz** [comment]
These instructions are useful, but let's keep on trying to get iOS online... :)

**Pull request merged**
